site_name: Linux内核
site_description: Linux内核
site_author: mestarz
site_url: https://mestarz.github.io/
repo_name: mestarz/mestarz-os
repo_url: https://github.com/mestarz/mestarz-os
copyright: Copyright &copy; 2020-2021 mestarz
theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: ./static/img/logo.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- 介绍:
  - index.md
  - 介绍/内核结构介绍.md
  - 介绍/源码浏览方法.md
  - 介绍/相关工具介绍.md
- 内核调试:
  - 内核调试/编译内核.md
  - 内核调试/使用QEMU运行内核.md
  - 内核调试/使用GDB调试内核.md
  - 内核调试/使用树莓派运行内核.md
- 进程管理:
  - 进程管理/进程生命周期.md
  - 进程管理/进程描述符.md
  - 进程管理/进程状态.md
  - 进程管理/进程家族树.md
  - 进程管理/进程创建.md
  - 进程管理/进程终止.md
- 进程调度:
  - 进程调度/进程调度.md
  - 进程调度/调度策略.md
  - 进程调度/调度算法.md
  - 进程调度/调度实现.md
  - 进程调度/抢占.md
  - 进程调度/上下文切换.md
  - 进程调度/实时调度策略.md
  - 进程调度/相关系统调用.md
markdown_extensions:
- admonition
- md_in_html
- codehilite:
    guess_lang: false
- def_list
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra_javascript:
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
- static/css/extra.css
