site_name: Linux内核
site_description: Linux内核
site_author: mestarz
copyright: Copyright &copy; 2020-2021 mestarz
theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: ./static/img/logo.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- Start:
  - index.md
- 内核调试:
  - 内核调试/编译内核.md
  - 内核调试/使用QEMU运行内核.md
  - 内核调试/使用GDB调试内核.md
  - 内核调试/使用树莓派运行内核.md